#!/bin/bash

# 远程数据库配置（用于备份）
DB_HOST='127.0.0.1'
DB_PORT=3306
DB_USER=root
DB_PASSWORD=your_password
DB_NAME="all_databases"

# 服务器配置
SERVER_USER="your_linux_account"
SERVER_IP="ip/or/dns"
SERVER_SSH_PORT=22
SERVER_BACKUP_PATH="/home/path/to/your/mariadb_backups"

# 本地数据库配置
LOCAL_DB_HOST="127.0.0.1"
LOCAL_DB_PORT="3306"
LOCAL_DB_USER="root"
LOCAL_DB_PASS="yourpasswords"